### ISSUE TITLE
Test file on branch 'master'

### ISSUE THREAD

**Issue by RemiRigal** [QuentinCar/Hexabot#11]
The file [`test.py`](https://github.com/QuentinCar/Hexabot/blob/master/workspaceRos/src/phantomx/phantomx_gazebo/scripts/test.py) in package `phantomx_gazebo` is not supposed to be on branch 'master'.

**Comment by QuentinCar** [comment]
Delete test.py, was here by mistake

**Comment by QuentinCar** [comment]
[commit](https://github.com/QuentinCar/Hexabot/commit/9dfa627745f833c9c3127590bae649f2c0cc5537)
