### ISSUE TITLE
Missing dependencies and how to launch the simulation in README.md

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#12]
Please complete your [README.md](https://github.com/QuentinCar/Hexabot/blob/master/README.md).

**Comment by QuentinCar** [comment]
Add dependencies and how to launch in ReadMe.md

**Comment by QuentinCar** [comment]
[commit](https://github.com/QuentinCar/Hexabot/commit/24b8f4b7af504f7d855ef057f9ecaf6b25e9a62f)
