### ISSUE TITLE
Cannot launch markerdisplay_marker and follow_wal nodes

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#21]
I followed the "Démarrer la simulation" section of the readme, but both _rosrun_ commands did'nt work:

`rosrun phantomx_marker markerdisplay_marker`
`> [rospack] Error: package 'phantomx_marker' not found`
Even with the right package name:
`rosrun phantomx_markers markerdisplay_marker`
`> [rosrun] Couldn't find executable named markerdisplay_marker below [...]`

`rosrun phantomx_gazebo follow_wall.py`
`> NameError: global name 'd_mur' is not defined`

Please help me !

**Comment by QuentinCar** [comment]
Solved your issue but other problems will appear. This software is still in development this part will be fully fonctioning soon. While waiting you can still launch it but whitout any points' display on rviz.
[rviz](https://github.com/QuentinCar/Hexabot/commit/f25853f6d3d4d6ef58969413378d77925f610446) 
[follow wall](https://github.com/QuentinCar/Hexabot/commit/8b5231ae8df0fb2f09221b372050e42c721da816)
