### ISSUE TITLE
I don't understand the usefulness of pictures folder

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#22]
Why have you put screenshots in the [pictures](https://github.com/QuentinCar/Hexabot/tree/master/pictures) folder ?

**Comment by porlanax** [comment]
It was in order to have some images before having a subscriber. We will remove it, it is useless now.

**Comment by QuentinCar** [comment]
[commit](https://github.com/QuentinCar/Hexabot/commit/d7e19b5c4300ba3cfe8acec2b8b74782fe59ca1a)
