### ISSUE TITLE
Useless binary file

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#23]
You have a .pyc file [here](https://github.com/QuentinCar/Hexabot/blob/master/workspaceRos/src/phantomx/phantomx_gazebo/src/phantomx_gazebo/phantomx.pyc)

**Comment by cyrilcotsaftis** [comment]
Issue solved, thanks !

**Comment by cyrilcotsaftis** [comment]
[link](https://github.com/QuentinCar/Hexabot/commit/6490646e4ead87b479514fbe9785143013e54506)
