### ISSUE TITLE
Several issues in trace_fissure.py

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#25]
The file [trace_fissure.py](https://github.com/QuentinCar/Hexabot/blob/master/workspaceRos/src/phantomx/phantomx_gazebo/scripts/trace_fissure.py) contains:

- indentation errors
- function Callback starting with a uppercase letter
- the file doesn't do anything yet, so why it is on branch master ?

**Comment by AlexandreArgento** [comment]
[commit link](https://github.com/QuentinCar/Hexabot/commit/16b573cb42fc93aa4ffb6333578b2795b0895db7)
