### ISSUE TITLE
Little enhancement

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#26]
These lines can be written in one line. It will be more comprehensible.

https://github.com/QuentinCar/Hexabot/blob/41d52b72b0a688df2e5cf0d28fa48c984014b84c/workspaceRos/src/phantomx/phantomx_gazebo/src/phantomx_gazebo/phantomx.py#L101-L105

**Comment by cyrilcotsaftis** [comment]
[enhancement done](https://github.com/QuentinCar/Hexabot/commit/15a57b447e2d0b96ecb5aea4e3e45cf208c8def4)
