### ISSUE TITLE
Bad declaration order in 'phantomx.py'

### ISSUE THREAD

**Issue by RemiRigal** [QuentinCar/Hexabot#27]
The publisher `_pub_coord_fissures` is used in the subscriber's callback `camera_callback` but it is declared after the subscriber, an error might occur.
Always declare Publishers before Subscribers.

https://github.com/QuentinCar/Hexabot/blob/9bd77b75ddf46594e081562a7779e2df964b9d3a/workspaceRos/src/phantomx/phantomx_gazebo/src/phantomx_gazebo/phantomx.py#L43-L48

**Comment by cyrilcotsaftis** [comment]
Issue solved.

**Comment by RemiRigal** [comment]
Please reference the pull request.

**Comment by QuentinCar** [comment]
[commit](https://github.com/QuentinCar/Hexabot/commit/6a52a1cfc560d5cb9456cb32b6c929d49adf296d)
