### ISSUE TITLE
Cannot launch the simu

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#28]
Mistakes in the names of the launch files.

https://github.com/QuentinCar/Hexabot/blob/79ce17fa96d339f2245c0a9ef3de6105e83b53df/README.md#L15-L17

**Comment by porlanax** [comment]
[Issue solved](https://github.com/QuentinCar/Hexabot/commit/d582397d721c25179094a19e767547d57c3c2870)

**Comment by TilletJ** [comment]
There are still 2 mistakes left L15 and L16.

**Comment by TilletJ** [comment]
Please unclose this issue @porlanax.

**Comment by cyrilcotsaftis** [comment]
[Issue solved](https://github.com/QuentinCar/Hexabot/blob/master/README.md)
