### ISSUE TITLE
Use of 'print' function for logging

### ISSUE THREAD

**Issue by RemiRigal** [QuentinCar/Hexabot#29]
https://github.com/QuentinCar/Hexabot/blob/4c1ad54d0b6de340de960378c1c93a40999d070c/workspaceRos/src/phantomx/phantomx_gazebo/src/phantomx_gazebo/phantomx.py#L66

**Comment by cyrilcotsaftis** [comment]
[print removed](https://github.com/RemiRigal/Hexabot/commit/72e4598d3f279b6d4800f673037adc56066a2879)
