### ISSUE TITLE
List index out of range in 'follow_wall.py'

### ISSUE THREAD

**Issue by RemiRigal** [QuentinCar/Hexabot#36]
![Issue_follow_wall](https://user-images.githubusercontent.com/19256051/72909569-87428280-3d37-11ea-873e-387b7818f0d5.png)

**Comment by cyrilcotsaftis** [comment]
[done](https://github.com/QuentinCar/Hexabot/commit/bc6f02509eead3551ac8ab0b396f1391bed8364c)
